Search_module/urls.py
from django.contrib import admin
from django.urls import path
from parsers import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('queries_list/', views.QueryListView.as_view(), name='queries_list'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('query_detail/<slug:slug>/', views.UserQueryDetail.as_view(), name='query_detail'),
    path('', views.new_query, name='new_query'),
    path('dash/', views.Dash.as_view(), name='dash')
]

parsers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class UserQueryManager(models.Manager):
    def all(self):
        return self.order_by('-id')


class Tags(models.Model):
    name_tag = models.CharField(max_length=255)


class UserQuery(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    timestamp = models.CharField(max_length=255, unique=True)
    author = models.CharField(max_length=255, default="")
    title = models.CharField(max_length=255, default="")
    keywords = models.CharField(max_length=255, default="")
    year1 = models.CharField(max_length=4, default="")
    year2 = models.CharField(max_length=4, default="")
    tags = models.ManyToManyField(Tags)
    objects = UserQueryManager()

    def get_url(self):
        return "/query_detail/{}/".format(self.timestamp)

    def get_absolute_url(self):
        return reverse('query_detail', kwargs={'timestamp': self.timestamp})

    def get_date(self):
        date = self.timestamp.split('-')
        date_line = date[2] + '.' + date[1] + '.' + date[0] + ' в ' + date[3] + ':' + date[4]
        if not self.user:
            user = 'Anonymous'
        else:
            user = self.user
        return 'Запрос от {} выполнен {}'.format(str(user), date_line)

    def get_name(self):
        date = self.timestamp.split('-')
        date_line = date[2] + '.' + date[1] + '.' + date[0] + ' в ' + date[3] + ':' + date[4]
        if not self.user:
            user = 'Anonymous'
        else:
            user = self.user
        return '{}: {}'.format(str(user), date_line)

    def keywords_to_socionet(self):
        if self.title:
            return self.title + ' ' + self.keywords
        return self.keywords

    def __str__(self):
        return self.timestamp


class Document(models.Model):
    user_query = models.ForeignKey(UserQuery, on_delete=models.CASCADE)
    local_url = models.FilePathField(max_length=600)
    net_url = models.URLField(max_length=600)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class BaseUrlParser(models.Model):
    user_query = models.ForeignKey(UserQuery, on_delete=models.CASCADE)
    url_cyberleninka = models.URLField(max_length=600)
    url_scholar = models.URLField(max_length=600)
    url_socio = models.URLField(max_length=600)

    def __str__(self):
        return 'Base url #' + str(self.id)

parsers/forms.py
from django import forms
import re


class NewQueryFrom(forms.Form):
    author = forms.CharField(max_length=255, required=False)
    title = forms.CharField(max_length=255, required=False)
    keywords = forms.CharField(max_length=255, required=False)
    year1 = forms.CharField(max_length=4, required=False)
    year2 = forms.CharField(max_length=4, required=False)

    def clean(self):
        year1 = self.cleaned_data.get('year1')
        year2 = self.cleaned_data.get('year2')
        if year2 and year1 and year2 < year1:
            raise forms.ValidationError('Неверно указан год')

    # def clean_author(self):
    #     author = self.cleaned_data.get('author')
    #     pattern = r'^[А-Я][а-я]+ [А-Я]\. [А-Я]\.$'
    #     if re.match(pattern, author):
    #         return author
    #     raise forms.ValidationError('Имя автора некорректно')

parsers/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

from parsers.main import main
from parsers.parser_engine.set_timestamp import set_timestamp
from parsers.models import UserQuery, Document, BaseUrlParser, Tags
from parsers.forms import NewQueryFrom


class Dash(ListView):
    model = UserQuery
    template_name = 'parsers/dash.html'


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "parsers/register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "parsers/login.html"
    success_url = "/"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")


class QueryListView(ListView):
    model = UserQuery
    context_object_name = 'userquerys'
    paginate_by = 4


class SearchView(QueryListView):
    def get(self, request, *args, **kwargs):
        tag_name = request.GET.get('tag')
        tag = get_object_or_404(Tags, name_tag=tag_name)
        queries = tag.userquery_set.all()
        context = {
            'userquerys': queries,
        }
        # return render_to_response(template_name='parsers/userquery_list.html', context=context)
        return render(request, 'parsers/userquery_list.html', context)


def new_query(request):
    if request.method == 'POST':
        form = NewQueryFrom(request.POST)
        if form.is_valid():
            set_timestamp()
            result = main(**form.cleaned_data)
            query = UserQuery(**result['UserQuery'])
            query.user_id = request.user.id
            query.save()
            for tag_name in list(result['UserQuery'].values())[1:]:
                if tag_name:
                    tag, _ = Tags.objects.get_or_create(name_tag=tag_name)
                    query.tags.add(tag)
            for doc in result['Document']:
                doc['user_query_id'] = int(query.id)
                document = Document(**doc)
                document.save()
            result['BaseUrlParser']['user_query_id'] = int(query.id)
            baseurl = BaseUrlParser(**result['BaseUrlParser'])
            baseurl.save()
            url = query.get_url()
            data = {
                'url': url,
                'message': 'ok'
            }
            return JsonResponse(data)
        data = {
            'url': '/',
            'message': 'form is not validate'
        }
        return JsonResponse(data)
    else:
        form = NewQueryFrom()
    return render(request, 'parsers/new_query.html', {
        'form': form
    })


class UserQueryDetail(DetailView):
    model = UserQuery
    slug_field = 'timestamp'

parsers/templates/parsers/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="{% static 'img/logo.jpg' %}">
    <title>{% block title %}Модуль поиска{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <a class="navbar-brand" href="">
            <img src="{% static 'img/IU5logo.gif' %}" width="50" height="50">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">

            <ul class="navbar-nav mr-auto">

                <li class="nav-item {% block new_query %}{% endblock %}">
                    <a class="nav-link" href="{% url 'new_query' %}">Новый запрос <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item {% block query_list %}{% endblock %}">
                    <a class="nav-link" href="{% url 'queries_list' %}">Список</a>
                </li>

                <li class="nav-item {% block dash_view %}{% endblock %}">
                    <a class="nav-link" href="{% url 'dash' %}">Статистика</a>
                </li>
                {% block search %}
                {% endblock %}


            </ul>

            <div class=" row my-2 my-lg-0">
                {% if not user.is_authenticated %}
                    <a class="col nav-link" href="{% url 'login' %}">Войти</a>
                {% else %}
                    <span class="col text-center my-auto" style="color: #1c7430">{{ user }}</span>
                    <a class="col nav-link" href="{% url 'logout' %}">Выйти</a>
                {% endif %}
            </div>

        </div>
    </nav>
</header>


<!-- Begin page content -->
<main role="main" class="container-fluid">

    <div class="container">
        <div class="row p-3">
            {% block content_title %}
            {% endblock %}
        </div>
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>



<script type="application/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
{#<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}

<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

parsers/templates/parsers/dash.html
{% extends 'parsers/base.html' %}

{% block dash_view %}active{% endblock %}

{% block content_title %}
    <div class="col text-center">
        <h3>Статистика</h3>
    </div>
{% endblock %}

{% block content %}

    <div class="col-md-9 ml-sm-auto mx-auto col-lg-10">
        <canvas  id="myChart" width="900" height="380"></canvas>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [
                    {% for query in object_list %}
                        {% if query.document_set.count %}
                            "{{ query.get_name }}",
                        {% endif %}
                    {% endfor %}
                ],
                datasets: [{
                    data: [
                        {% for query in object_list.reverse %}
                            {% if query.document_set.count %}
                                {{ query.document_set.count }},
                            {% endif %}
                        {% endfor %}
                    ],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#007bff',
                    borderWidth: 4,
                    pointBackgroundColor: '#007bff'
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: false
                        }
                    }]
                },
                legend: {
                    display: false,
                }
            }
        });
    </script>

{% endblock %}

parsers/templates/parsers/load.html
{% extends 'parsers/base.html' %}

{% block content %}
    Идет загрузка....
{% endblock %}

parsers/templates/parsers/login.html
{% extends 'parsers/base.html' %}

{% block content_title %}
{% endblock %}

{% block content %}
    <div class="col-6 mx-auto">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Имя пользователя:</label>
                <input type="text" class="form-control" name="username" autofocus maxlength="254" required id="id_username" />
            </div>

            <div class="form-group">
                <label for="id_password">Пароль:</label>
                <input type="password" class="form-control" name="password" required id="id_password" />
            </div>
            <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Войти</button>
        </form>
        <a href="{%  url 'register' %}" class="btn btn-lg btn-primary btn-block mt-2">Зарегистрироваться</a>
    </div>
{% endblock %}

parsers/templates/parsers/new_query.html
{% extends 'parsers/base.html'%}
{% load staticfiles %}
{% block title %}
    Новый запрос
{% endblock %}

{% block new_query %}active{% endblock %}

{% block content_title %}
    <div class="col text-center">
        <h3 id="title">Тематический поиск научных материалов</h3>
    </div>
{% endblock %}



{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="col-6 mx-auto" id="form_query">
        <form action="{% url 'new_query' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="col">
                    <div class="form-group">
                        <label for="exampleInputAuthor">Автор</label>
                        <input type="text" class="form-control" id="exampleInputAuthor" placeholder="Иванов И. И." name="author"
                               aria-describedby="Author" value="">
                        <small id="Author">Автор только один</small>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputTitle">Название статьи</label>
                        <input type="text" class="form-control" id="exampleInputTitle" placeholder="Автоматизированные системы" name="title"
                               aria-describedby="Title"
                               value="">
                        <small id="Title"></small>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputKeyWords">Ключевые слова</label>
                        <input type="text" class="form-control" id="exampleInputKeyWords" placeholder="кибернетика тестирование" name="keywords"
                               aria-describedby="Keywords"
                               value="">
                        <small id="Keywords">Ключевые слова через пробел</small>
                    </div>
                    <div>
                        <label for="exampleInputYear1">Показать статьи, датированные следующим <b>периодом</b>:</label>
                    </div>
                </div>
            </div>
            <div class="form-row">

                <div class="col-5 col-xs-12">
                    <div class="form-group">
                        <input name="year1" class="form-control" value="" id="exampleInputYear1" placeholder="2017" maxlength="4" pattern="[0-9]*" type="text">
                    </div>
                </div>
                <span class="col-2 col-xs-12 text-center"> — </span>
                <div  class="col-5 col-xs-12">
                    <div class="form-group">
                        <input name="year2" class="form-control" value="" id="xampleInputYear2" placeholder="2018" maxlength="4" pattern="[0-9]*" type="text">
                    </div>
                </div>

            </div>
            <button type="submit" class="btn btn-lg btn-block btn-primary" >Найти</button>

        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        function loadDoc() {
            {#console.log('загружаем');#}
            $("#title").text ("Загрузка материалов....");
            $("#form_query").html ("<div class=\"row justify-content-center\"><img src='{% static 'img/25.gif' %}'></div>")
        }

        $(function() {
            $('form').submit(function (e) {
                var $form = $(this);
                $.ajax({
                    type: $form.attr('method'),
                    url: $form.attr('action'),
                    beforeSend: loadDoc,
                    data: $form.serialize()
                }).done(function (data) {
                    $("#title").text("Загрузка завершена");
                    $("#form_query").html("<h4>" + data.message + "</h4>");
                    document.location.href = data.url;
                    {#console.log('загрузили');#}
                }).fail(function () {
                    {#console.log('fail');#}
                });
                //отмена действия по умолчанию для кнопки submit
                e.preventDefault();
            })
        });

    </script>
{% endblock %}

parsers/templates/parsers/register.html
{% extends 'parsers/base.html' %}

{% block content_title %}
{% endblock %}

{% block content %}
    <div class="col-6 mx-auto">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Имя пользователя:</label>
                <input type="text" class="form-control" name="username" maxlength="150" autofocus required id="id_username" />
                <small class="helptext">150 символов или меньше. Буквы, цифры и @/./+/-/_ .</small>
            </div>

            <div class="form-group">
                <label for="id_password1">Пароль:</label>
                <input type="password" class="form-control" name="password1" required id="id_password1" />
                <small class="helptext">
                    <ul>
                        <li>Ваш пароль не должен быть похож на логин.</li>
                        <li>Ваш пароль должен содержать не менее 8 знаков.</li>
                        <li>Ваш пароль не должен быть слишком простым.</li>
                        <li>Ваш пароль не может быть только числовым.</li>
                    </ul>
                </small>
            </div>

            <div class="form-group">
                <label for="id_password2">Подтверждение пароля:</label>
                <input type="password" class="form-control" name="password2" required id="id_password2" />
                <small class="helptext">Повторите ввод пароля</small>
            </div>
            <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Зарегистрироваться</button>
        </form>
    </div>
{% endblock %}

parsers/templates/parsers/userquery_detail.html
{% extends 'parsers/base.html' %}



{% block content_title %}
    <div class="col-2">
        <a href="#" onclick="history.back();" class="btn btn-primary">Назад</a>
    </div>
    <div class="col-10">
        <h3 class="h3 justify-content-center">{{  object.get_date }}</h3>
    </div>
{% endblock %}


{% block content %}
    <div class="col-md-3 col-xs-12">
        <div class="row">
            <div class="col-xs-12">
                <h4>Параметры запроса:</h4>
                {% if object.author %}
                    <span class="pl-3">Автор: {{ object.author }}</span><br>
                {% endif %}
                {% if object.title %}
                    <span class="pl-3">Заголовок: {{ object.title }}</span><br>
                {% endif %}
                {% if object.keywords %}
                    <span class="pl-3">Ключевые слова: {{ object.keywords }}</span><br>
                {% endif %}
                {% if object.year1 or object.year2 %}
                    <span class="pl-3">
                            {% if object.year1 %}
                                c {{ object.year1 }}
                            {% endif %}
                        {% if object.year2 %}
                            по {{ object.year2 }}
                        {% endif %}
                        </span>
                {% endif %}
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-xs-12">
                <h4>Выполненные запросы:</h4>
                <ol type="None">
                    <li class="m-1"><a href="{{ object.baseurlparser_set.first.url_cyberleninka }}" class="btn btn-outline-primary" target="_blank">cyberleninka.ru</a></li>
                    <li class="m-1"><a href="{{ object.baseurlparser_set.first.url_scholar }}" class="btn btn-outline-primary" target="_blank">scholar.goolge.com</a></li>
                    <li class="m-1">
                        <form action="{{ object.baseurlparser_set.first.url_socio }}" method="POST" target="_blank">
                            <input hidden value="{{ object.keywords_to_socionet }}" name="justtext">
                            <input hidden value="{{ object.author }}" name="author-name">
                            <input hidden value="fulltext" name="fulltext">
                            <input hidden value="{{ object.year1 }}" name="tr1">
                            <input hidden value="{{ object.year2 }}" name="tr2">
                            <input hidden value="utf-8" name="accept-charset">
                            <input type=submit class="btn btn-outline-primary" value="socionet.ru">
                        </form>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <div class="col-md-9 col-xs-12">
        <h4>Документов загружено {{ object.document_set.count }}: </h4>
        {% if not object.document_set.all %}
            <span class="pl-3">Документов не найдено</span>
        {% endif %}
        <ul>
            {% for doc in object.document_set.all %}
                <p><li><a href="{{ doc.net_url }}" target="_blank">{{ doc.title }}</a></li></p>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

parsers/templates/parsers/userquery_list.html
{% extends 'parsers/base.html' %}

{% block title %}
    Список запросов
{% endblock %}

{% block content_title %}
    <div class="col text-center">
        <h3>Список запросов</h3>
    </div>
{% endblock %}

{% block search %}
    <li class="nav-item ml-2 my-auto">
        <form action="{% url 'search' %}" class="form-inline my-2 my-lg-0" method="get">
            <input class="form-control mr-sm-2" type="text" required name="tag" placeholder="Поиск по запросам" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
    </li>
{% endblock %}

{% block query_list %}active{% endblock %}

{% block content %}
    <div class="row w-100">
        <div class="col mx-auto">
            <div class="card-deck justify-content-center">
                {% for query in userquerys %}

                    <div class="card m-2" style="max-width: 18rem;">
                        <div class="card-header">
                            <p class="card-title">{{ query.get_name }}</p>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                {% if query.author %}
                                    <span class="pl-3">Автор: {{ query.author }}</span><br>
                                {% else %}
                                    <span class="pl-3">Автор: --</span><br>
                                {% endif %}
                                {% if query.title %}
                                    <span class="pl-3">Заголовок: {{ query.title }}</span><br>
                                {% else %}
                                    <span class="pl-3">Заголовок: --</span><br>
                                {% endif %}
                                {% if query.keywords %}
                                    <span class="pl-3">Ключевые слова: {{ query.keywords }}</span><br>
                                {% else %}
                                    <span class="pl-3">Ключевые слова: --</span><br>
                                {% endif %}
                                {% if query.year1 or query.year2 %}
                                    <span class="pl-3">Период:
                                        {% if query.year1 %}
                                            c {{ query.year1 }}
                                        {% endif %}
                                        {% if query.year2 %}
                                            по {{ query.year2 }}
                                        {% endif %}
                            </span><br>
                                {% else %}
                                    <span class="pl-3">Период: --  </span><br>
                                {% endif %}

                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="/query_detail/{{ query.timestamp }}" class="btn btn-primary">Подробнее</a>
                        </div>
                    </div>


                {% endfor %}
            </div>


        </div>
    </div>
    <div class="row mx-auto mt-2">
        <div class="col">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo; first</a>
                    </li>
                    <li>
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                    </li>
                {% endif %}

                {% for page in page_obj.paginator.page_range %}
                    <li class="page-item {% if page == page_obj.number %} active {% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}


                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>

{% endblock %}